"""Build the interactive offline research viewer."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd

REPORTS = Path("reports")
OUTPUT = REPORTS / "research_viewer.html"


def _returns(frame: pd.DataFrame) -> dict[str, list[float]]:
    return {column: frame[column].fillna(0).astype(float).tolist() for column in frame}


def build_payload() -> dict[str, object]:
    stats = pd.read_csv(REPORTS / "backtest_stats.csv").to_dict("records")
    alpha_stats = pd.read_csv(REPORTS / "alpha_backtest_stats.csv").to_dict("records")[0]
    alpha_equity = pd.read_csv(REPORTS / "alpha_backtest_equity.csv", index_col=0).iloc[:, 0].ffill().fillna(1).tolist()
    factors = pd.read_csv(REPORTS / "oos_latent_factor_moves.csv", index_col=0, parse_dates=True)
    fitted = pd.read_csv(REPORTS / "strategy_oos_fitted.csv", index_col=0, parse_dates=True)
    residual = pd.read_csv(REPORTS / "strategy_oos_residuals.csv", index_col=0, parse_dates=True)
    raw = pd.read_csv(REPORTS.parent / "data/raw/daily_returns.csv", index_col=0, parse_dates=True)[fitted.columns].loc[fitted.index]
    cluster = pd.read_csv(REPORTS / "benchmark_cluster_order.csv")["ticker"].tolist()
    benchmark_returns = pd.read_csv(REPORTS.parent / "data/raw/daily_returns.csv", index_col=0, parse_dates=True)[cluster].loc[factors.index]
    benchmark_mean = benchmark_returns.ewm(alpha=0.01, adjust=False).mean()
    benchmark_volatility = (benchmark_returns - benchmark_mean).pow(2).ewm(alpha=0.01, adjust=False).mean().pow(0.5).bfill().mean(axis=1)
    factor_returns = factors.mul(benchmark_volatility, axis=0)
    loadings = pd.read_csv(REPORTS / "frozen_factor_loadings.csv", index_col=0)
    betas = pd.read_csv(REPORTS / "strategy_train_exposures.csv", index_col=0)
    raw_corr, residual_corr = raw.corr(), residual.corr()
    scatter = []
    for index, left in enumerate(raw.columns):
        for right in raw.columns[index + 1:]:
            x, y = float(raw_corr.loc[left, right]), float(residual_corr.loc[left, right])
            scatter.append({"a": left, "b": right, "raw": x, "residual": y, "delta": y - x})
    return {
        "stats": stats,
        "alpha": alpha_stats,
        "alpha_equity": alpha_equity,
        "dates": [str(date.date()) for date in fitted.index],
        "factors": {"names": list(factor_returns), "values": _returns(factor_returns)},
        "loadings": loadings.to_dict("index"),
        "betas": betas.to_dict("index"),
        "funds": {"names": list(fitted), "raw": _returns(raw), "fitted": _returns(fitted), "residual": _returns(residual)},
        "benchmarks": cluster,
        "scatter": scatter,
    }


def render(payload: dict[str, object]) -> str:
    data = json.dumps(payload, separators=(",", ":"))
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Factor Model Research Viewer</title>
<style>
:root{{--ink:#17282e;--muted:#68787b;--paper:#f4f1e8;--panel:#fffdf8;--line:#d5d4ca;--teal:#176b87;--green:#2f855a;--red:#b94a48;--blue:#2e67a5;--gold:#b87919}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 Georgia,serif;background-image:linear-gradient(rgba(23,107,135,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(23,107,135,.035) 1px,transparent 1px);background-size:34px 34px}}
.shell{{max-width:1480px;margin:auto;padding:26px 32px 60px}} header{{border-bottom:2px solid var(--ink);padding-bottom:20px;display:flex;justify-content:space-between;gap:24px}} .kicker,.ui{{font:700 11px 'Segoe UI',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:var(--teal)}} h1{{font-size:clamp(35px,5vw,68px);line-height:.98;font-weight:500;margin:10px 0;max-width:850px}} .lede,.intro{{color:var(--muted);font-size:17px;max-width:950px}} .meta{{font:12px 'Segoe UI',sans-serif;color:var(--muted);text-align:right}}
.layout{{display:grid;grid-template-columns:220px 1fr;gap:28px;margin-top:25px}} nav{{position:sticky;top:15px;align-self:start;display:grid;gap:7px}} nav button,.legend button{{border:1px solid var(--line);background:var(--panel);padding:9px 11px;text-align:left;cursor:pointer;color:var(--ink)}} nav button.active,nav button:hover{{background:var(--ink);color:#fff;border-color:var(--ink)}} .chapter{{display:none}} .chapter.active{{display:block;animation:up .3s ease}} @keyframes up{{from{{opacity:0;transform:translateY(8px)}}to{{opacity:1;transform:none}}}}
h2{{font-size:37px;line-height:1.05;font-weight:500;margin:0 0 8px}} h3{{font-size:21px;font-weight:500;margin:26px 0 8px}} .flow,.cards{{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid var(--ink);border-bottom:1px solid var(--ink);margin:24px 0}} .cards{{grid-template-columns:repeat(3,1fr);border:0;gap:10px}} .step,.card{{padding:15px;border-right:1px solid var(--line);background:rgba(255,253,248,.55)}} .step:last-child{{border:0}} .step b{{color:var(--teal);font:700 11px 'Segoe UI',sans-serif}} .step span{{display:block;margin-top:8px}} .card{{border:1px solid var(--line);background:var(--panel)}} .card b{{font-size:28px;font-weight:500;display:block;margin:5px 0}} .card small{{color:var(--muted);font:12px 'Segoe UI',sans-serif}} .note{{border-left:4px solid var(--teal);background:#e5efed;padding:13px 16px;color:#345057}}
.actions,.control,.legend{{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:17px 0}} .actions a{{color:var(--teal);font:13px 'Segoe UI',sans-serif;border-bottom:1px solid currentColor;text-decoration:none}} select{{border:1px solid var(--line);background:var(--panel);padding:10px;min-width:220px}} .chart,.tablewrap{{background:var(--panel);border:1px solid var(--line);padding:12px;margin-top:14px;overflow:auto}} .fundGrid{{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:14px;align-items:start}} svg{{display:block;width:100%;height:auto;min-height:300px}} .legend button.off{{opacity:.38;text-decoration:line-through}} .swatch{{display:inline-block;width:11px;height:11px;border:1px solid #718187;margin-right:5px}} table{{border-collapse:collapse;width:100%;font:12px 'Segoe UI',sans-serif}} th,td{{padding:8px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}} th:first-child,td:first-child{{text-align:left}} .tip{{position:fixed;display:none;pointer-events:none;background:var(--ink);color:#fff;padding:7px 9px;border-radius:2px;font:12px 'Segoe UI',sans-serif;z-index:2}}
@media(max-width:900px){{.shell{{padding:18px 14px}}header,.layout{{display:block}}.meta{{text-align:left;margin-top:16px}}nav{{position:static;display:flex;overflow:auto;margin-bottom:20px}}nav button{{white-space:nowrap}}.flow,.cards,.fundGrid{{grid-template-columns:1fr}}.step{{border-right:0;border-bottom:1px solid var(--line)}}}}
</style></head><body><div id="tip" class="tip"></div><div class="shell"><header><div><div class="kicker">Statistical factor risk model · research viewer</div><h1>From benchmark structure to residual alpha.</h1><p class="lede">An interactive audit of the benchmark universe, frozen factor construction, hidden fund betas, residual performance, and the equal-risk alpha portfolio.</p></div><div class="meta">Offline HTML<br>Frozen loading space<br>Out-of-sample scoring</div></header>
<div class="layout"><nav><button class="active" data-tab="start">01 · Start here</button><button data-tab="universe">02 · Universes</button><button data-tab="factors">03 · Frozen factors</button><button data-tab="funds">04 · Fund selector</button><button data-tab="correlations">05 · Correlations</button><button data-tab="strategies">06 · Strategies</button></nav><main>
<section id="start" class="chapter active"><div class="kicker">Research map</div><h2>What is being explained, and what is left?</h2><p class="intro">Benchmark assets define the hidden risk space. Investible funds are held out from factor construction, regressed on daily latent factor moves, and stripped to residual returns. The alpha sleeve trades only that residual panel.</p><div class="flow"><div class="step"><b>BENCHMARKS</b><span>Clustered assets define the risk vocabulary.</span></div><div class="step"><b>LOADINGS</b><span>Chunked PCA loadings are aligned, averaged, and frozen.</span></div><div class="step"><b>FACTOR MOVES</b><span>Daily benchmark regressions estimate latent innovations OOS.</span></div><div class="step"><b>FUNDS</b><span>Training betas explain raw OOS performance.</span></div><div class="step"><b>ALPHA</b><span>Residuals feed the trend follower.</span></div></div><div class="cards"><article class="card"><span class="ui">Raw sleeve</span><b>10.2% vol</b><small>10.7% CAGR · 1.25x max leverage</small></article><article class="card"><span class="ui">Neutral sleeve</span><b>9.9% vol</b><small>2.1% CAGR · 2.50x max leverage</small></article><article class="card"><span class="ui">Residual alpha</span><b>32.7% CAGR</b><small>10.6% vol · Sharpe 2.72 · 9.0% drawdown</small></article></div><p class="note"><b>Reading guide:</b> inspect the loading matrix and cumulative factor paths, then use the correlation movement page before evaluating the portfolio charts.</p></section>
<section id="universe" class="chapter"><div class="kicker">Chapter 02 · Inputs</div><h2>Two universes, two jobs.</h2><p class="intro">The benchmark panel is the only source of factor definitions. The non-benchmark universe is investible research material and never defines the factor space.</p><div class="cards"><article class="card"><span class="ui">Benchmark assets</span><b id="benchmarkCount"></b><small>clustered for model diagnostics</small></article><article class="card"><span class="ui">Investible funds</span><b id="fundCount"></b><small>residuals become alpha inputs</small></article><article class="card"><span class="ui">OOS observations</span><b id="obsCount"></b><small>daily latent moves and fund scoring</small></article></div><p class="note">Clustering and the frozen loading matrix are shown together on the next page, where they describe the actual model inputs rather than a standalone ranking.</p></section>
<section id="universe" class="chapter"><div class="kicker">Chapter 02 · Inputs</div><h2>Two universes, two jobs.</h2><p class="intro">The benchmark panel is the only source of factor definitions. The non-benchmark universe is investible research material and never defines the factor space.</p><div class="cards"><article class="card"><span class="ui">Benchmark assets</span><b id="benchmarkCount"></b><small>clustered for model diagnostics</small></article><article class="card"><span class="ui">Investible funds</span><b id="fundCount"></b><small>residuals become alpha inputs</small></article><article class="card"><span class="ui">OOS observations</span><b id="obsCount"></b><small>daily latent moves and fund scoring</small></article></div><h3>Ordered frozen loading matrix</h3><div id="loadingHeatmap" class="tablewrap"></div><p class="note">Rows follow the hierarchical benchmark order. Red and blue show positive and negative loadings; white is zero. Factor definitions are frozen before OOS fund scoring.</p></section>
<div class="actions"><a href="frozen_factor_loadings.csv">Frozen loading matrix CSV</a><a href="oos_latent_factor_moves.csv">OOS factor moves CSV</a></div><div id="loadTable" class="tablewrap" style="display:none"></div><div class="chart"><div id="factorLegend" class="legend"></div><svg id="factorChart" viewBox="0 0 1000 460"></svg></div></section>
<section id="factors" class="chapter"><div class="kicker">Chapter 03 · Frozen factor model</div><h2>Loadings first. Factor returns second.</h2><p class="intro">Historical benchmark blocks are PCA-decomposed, aligned, averaged, and frozen. The chart compounds the daily OOS latent factor moves, with dates on the axis so persistence and regime changes are visible.</p><div class="actions"><a href="frozen_factor_loadings.csv">Frozen loading matrix CSV</a><a href="oos_latent_factor_moves.csv">OOS factor moves CSV</a></div><div id="loadTable" class="tablewrap"></div><div class="chart"><div id="factorLegend" class="legend"></div><svg id="factorChart" viewBox="0 0 1000 460"></svg></div></section>
<section id="funds" class="chapter"><div class="kicker">Chapter 04 · Hidden betas</div><h2>Choose a fund. See the explanation.</h2><p class="intro">The selector drives the raw, factor-fitted, and residual performance chart. The statistics table stays beside it on wide screens and stacks below on mobile.</p><div class="control"><label class="ui" for="fundSelect">Fund</label><select id="fundSelect"></select></div><div class="fundGrid"><div><div id="fundLegend" class="legend"></div><div class="chart"><svg id="fundChart" viewBox="0 0 1000 460"></svg></div></div><div id="fundStats" class="tablewrap"></div></div><div id="betaTable" class="tablewrap"></div></section>
<section id="correlations" class="chapter"><div class="kicker">Chapter 05 · Correlation movement</div><h2>What changes when hidden beta is removed?</h2><p class="intro">Each point is a fund pair. The x-axis is raw correlation, the y-axis is residual correlation, and the diagonal marks no change. Hover any point for the pair and exact values; callouts identify the largest movements.</p><div class="chart"><svg id="scatter" viewBox="0 0 1000 650"></svg></div></section>
<section id="strategies" class="chapter"><div class="kicker">Chapter 06 · Portfolio construction</div><h2>Equal-weight funds, then trend follow.</h2><p class="intro">Raw and residual equal-weight fund benchmarks are compared with the trend follower on the residual matrix. Signals and volatility estimates are lagged one day.</p><div id="strategyLegend" class="legend"></div><div class="chart"><svg id="strategyChart" viewBox="0 0 1000 460"></svg></div><div id="strategyTable" class="tablewrap"></div><div class="actions"><a href="alpha_backtest_stats.csv">Alpha statistics CSV</a><a href="figures/residual_alpha_trend_follower.html">Detailed alpha report</a></div></section>
</main></div></div>
<script>const DATA={data};
const $=id=>document.getElementById(id), COLORS=['#176b87','#2f855a','#b87919','#b94a48','#2e67a5','#6b4f9e','#127c78','#9a5b13'];
function esc(v){{return String(v).replace(/[&<>"']/g,m=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[m]))}}
function cumulative(values){{let level=1;return values.map(value=>{{level*=1+(value||0);return level}})}}
function axis(svg,width,height,dates,min,max){{const ns='http://www.w3.org/2000/svg';const group=document.createElementNS(ns,'g');group.setAttribute('class','axes');const left=70,bottom=58,top=30,right=30;[0,.5,1].forEach((fraction)=>{{const y=top+(height-top-bottom)*fraction,line=document.createElementNS(ns,'line');line.setAttribute('x1',left);line.setAttribute('x2',width-right);line.setAttribute('y1',y);line.setAttribute('y2',y);line.setAttribute('stroke','#d5d4ca');group.appendChild(line);const label=document.createElementNS(ns,'text');label.setAttribute('x',left-9);label.setAttribute('y',y+4);label.setAttribute('text-anchor','end');label.setAttribute('font-size','12');label.textContent=(max-(max-min)*fraction).toFixed(2);group.appendChild(label)}});[0,.25,.5,.75,1].forEach((fraction)=>{{const x=left+(width-left-right)*fraction,label=document.createElementNS(ns,'text');label.setAttribute('x',x);label.setAttribute('y',height-20);label.setAttribute('text-anchor','middle');label.setAttribute('font-size','12');label.textContent=dates[Math.round((dates.length-1)*fraction)].slice(0,10);group.appendChild(label)}});svg.appendChild(group);return {{left,right,top,bottom}}}}
function draw(id,series,state,legendId,dates){{const svg=$(id),keys=Object.keys(series),shown=keys.filter(key=>state[key]),values=shown.flatMap(key=>series[key]).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values);svg.innerHTML='';$(legendId).innerHTML='';const box=axis(svg,1000,460,dates,min,max),ns='http://www.w3.org/2000/svg';keys.forEach((key,index)=>{{const button=document.createElement('button');button.className=state[key]?'':'off';button.innerHTML=`<span class="swatch" style="background:${{COLORS[index%COLORS.length]}}"></span>${{esc(key)}}`;button.onclick=()=>{{state[key]=!state[key];draw(id,series,state,legendId,dates)}};$(legendId).appendChild(button);if(!state[key])return;const points=series[key].map((value,point)=>`${{box.left+(1000-box.left-box.right)*point/Math.max(1,series[key].length-1)}},${{box.top+(460-box.top-box.bottom)*(max-value)/Math.max(1e-9,max-min)}}`).join(' '),line=document.createElementNS(ns,'polyline');line.setAttribute('points',points);line.setAttribute('fill','none');line.setAttribute('stroke',COLORS[index%COLORS.length]);line.setAttribute('stroke-width','3');svg.appendChild(line)}})}}
function stats(values){{const clean=values.filter(Number.isFinite),mean=clean.reduce((a,b)=>a+b,0)/clean.length,vol=Math.sqrt(clean.reduce((a,b)=>a+(b-mean)**2,0)/Math.max(1,clean.length-1))*Math.sqrt(252),equity=cumulative(clean);let peak=1,dd=0;equity.forEach(value=>{{peak=Math.max(peak,value);dd=Math.min(dd,value/peak-1)}});return {{mean,vol,cagr:Math.pow(equity[equity.length-1],252/clean.length)-1,maxdd:dd,sharpe:mean*Math.sqrt(252)/Math.max(vol,1e-9)}}}}
function fundView(){{const f=DATA.funds,name=$('fundSelect').value,index=f.names.indexOf(name),series={{Raw:cumulative(f.raw[name]),'Factor explained':cumulative(f.fitted[name]),Residual:cumulative(f.residual[name])}};draw('fundChart',series,{{Raw:true,'Factor explained':true,Residual:true}},'fundLegend',DATA.dates);let h='<table><thead><tr><th>Series</th><th>Ann vol</th><th>CAGR</th><th>Max DD</th><th>Sharpe</th></tr></thead><tbody>';[['Raw',f.raw[name]],['Factor explained',f.fitted[name]],['Residual',f.residual[name]]].forEach(([label,values])=>{{const s=stats(values);h+=`<tr><td>${{label}}</td><td>${{(s.vol*100).toFixed(1)}}%</td><td>${{(s.cagr*100).toFixed(1)}}%</td><td>${{(s.maxdd*100).toFixed(1)}}%</td><td>${{s.sharpe.toFixed(2)}}</td></tr>`}});$('fundStats').innerHTML=h+'</tbody></table>';const beta=DATA.betas[name]||{{}};h='<table><thead><tr><th>Training OLS exposure</th><th>Value</th></tr></thead><tbody>';Object.entries(beta).forEach(([key,value])=>h+=`<tr><td>${{esc(key)}}</td><td>${{Number(value).toFixed(5)}}</td></tr>`);$('betaTable').innerHTML=h+'</tbody></table>'}}
function renderScatter(){{const svg=$('scatter'),ns='http://www.w3.org/2000/svg',left=75,right=35,top=30,bottom=75,width=1000,height=650;svg.innerHTML='';for(let i=-1;i<=1;i+=.5){{const x=left+(width-left-right)*(i+1)/2,y=top+(height-top-bottom)*(1-(i+1)/2),v=document.createElementNS(ns,'line'),h=document.createElementNS(ns,'line');v.setAttribute('x1',x);v.setAttribute('x2',x);v.setAttribute('y1',top);v.setAttribute('y2',height-bottom);v.setAttribute('stroke','#d5d4ca');h.setAttribute('x1',left);h.setAttribute('x2',width-right);h.setAttribute('y1',y);h.setAttribute('y2',y);h.setAttribute('stroke','#d5d4ca');svg.append(v,h)}}const diagonal=document.createElementNS(ns,'line');diagonal.setAttribute('x1',left);diagonal.setAttribute('y1',height-bottom);diagonal.setAttribute('x2',width-right);diagonal.setAttribute('y2',top);diagonal.setAttribute('stroke','#17282e');diagonal.setAttribute('stroke-dasharray','7 5');diagonal.setAttribute('stroke-width','2');svg.appendChild(diagonal);const xlab=document.createElementNS(ns,'text');xlab.setAttribute('x',500);xlab.setAttribute('y',630);xlab.setAttribute('text-anchor','middle');xlab.textContent='Raw correlation';svg.appendChild(xlab);const ylab=document.createElementNS(ns,'text');ylab.setAttribute('x',18);ylab.setAttribute('y',330);ylab.setAttribute('transform','rotate(-90 18 330)');ylab.textContent='Residual correlation';svg.appendChild(ylab);const tip=$('tip');DATA.scatter.forEach(point=>{{const x=left+(width-left-right)*(point.raw+1)/2,y=top+(height-top-bottom)*(1-(point.residual+1)/2),strength=Math.min(1,Math.abs(point.delta)*4),positive=point.delta>=0,c=document.createElementNS(ns,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',6);c.setAttribute('fill',positive?`rgb(190,${{Math.round(115-55*strength)}},${{Math.round(110-45*strength)}})`:`rgb(${{Math.round(90-30*strength)}},${{Math.round(140-35*strength)}},${{Math.round(190-35*strength)}})`);c.setAttribute('stroke','#53636a');c.setAttribute('stroke-width','1.5');c.onmousemove=event=>{{tip.style.display='block';tip.style.left=event.clientX+12+'px';tip.style.top=event.clientY+12+'px';tip.innerHTML=`<b>${{esc(point.a)}} / ${{esc(point.b)}}</b><br>raw ${{point.raw.toFixed(3)}} · residual ${{point.residual.toFixed(3)}}<br>change ${{point.delta>=0?'+':''}}${{point.delta.toFixed(3)}}`}};c.onmouseleave=()=>tip.style.display='none';svg.appendChild(c)}});const labels=[...DATA.scatter].sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,4);labels.forEach((point,index)=>{{const x=left+(width-left-right)*(point.raw+1)/2,y=top+(height-top-bottom)*(1-(point.residual+1)/2),text=document.createElementNS(ns,'text');text.setAttribute('x',Math.min(width-right-100,x+10));text.setAttribute('y',Math.max(top+15,y-10-index%2*14));text.setAttribute('font-size','11');text.textContent=point.a+'/'+point.b;svg.appendChild(text)}})}}
function init(){{const f=DATA.funds;f.names.forEach(name=>$('fundSelect').add(new Option(name,name)));$('fundSelect').onchange=fundView;$('benchmarkCount').textContent=DATA.benchmarks.length;$('fundCount').textContent=f.names.length;$('obsCount').textContent=DATA.dates.length;let h='<table><thead><tr><th>Cluster order</th><th>Benchmark</th></tr></thead><tbody>';DATA.benchmarks.forEach((name,index)=>h+=`<tr><td>${{index+1}}</td><td>${{name}}</td></tr>`);$('loadTable').innerHTML='<table><thead><tr><th>Benchmark</th>'+Object.keys(DATA.loadings[DATA.benchmarks[0]]||{{}}).map(key=>`<th>${{key}}</th>`).join('')+'</tr></thead><tbody>'+DATA.benchmarks.map(name=>`<tr><td>${{name}}</td>`+Object.values(DATA.loadings[name]||{{}}).map(value=>`<td>${{Number(value).toFixed(4)}}</td>`).join('')+'</tr>`).join('')+'</tbody></table>';draw('factorChart',Object.fromEntries(DATA.factors.names.map(name=>[name,cumulative(DATA.factors.values[name])])),Object.fromEntries(DATA.factors.names.map(name=>[name,true])),'factorLegend',DATA.dates);const raw=DATA.funds.names.map(name=>DATA.funds.raw[name]).reduce((a,row)=>row.map((value,index)=>(a[index]||0)+value),[]).map(value=>value/f.names.length),res=DATA.funds.names.map(name=>DATA.funds.residual[name]).reduce((a,row)=>row.map((value,index)=>(a[index]||0)+value),[]).map(value=>value/f.names.length);draw('strategyChart',{{'Equal-weight raw funds':cumulative(raw),'Equal-weight residual funds':cumulative(res),'Residual alpha trend follower':DATA.alpha_equity}},{{'Equal-weight raw funds':true,'Equal-weight residual funds':true,'Residual alpha trend follower':true}},'strategyLegend',DATA.dates);h='<table><thead><tr><th>Strategy</th><th>Target vol</th><th>Realized vol</th><th>CAGR</th><th>Max DD</th><th>Sharpe</th></tr></thead><tbody>';DATA.stats.forEach(row=>h+=`<tr><td>${{row.strategy}}</td><td>${{(row.target_vol*100).toFixed(1)}}%</td><td>${{(row.annual_vol*100).toFixed(1)}}%</td><td>${{(row.cagr*100).toFixed(1)}}%</td><td>${{(row.max_drawdown*100).toFixed(1)}}%</td><td>${{row.sharpe.toFixed(2)}}</td></tr>`);h+=`<tr><td>Residual alpha</td><td>${{(DATA.alpha.target_vol*100).toFixed(1)}}%</td><td>${{(DATA.alpha.annual_vol*100).toFixed(1)}}%</td><td>${{(DATA.alpha.cagr*100).toFixed(1)}}%</td><td>${{(DATA.alpha.max_drawdown*100).toFixed(1)}}%</td><td>${{DATA.alpha.sharpe.toFixed(2)}}</td></tr></tbody></table>`;$('strategyTable').innerHTML=h;fundView();renderScatter()}}const tabs=[...document.querySelectorAll('nav button')],chapters=[...document.querySelectorAll('.chapter')];tabs.forEach(tab=>tab.onclick=()=>{{tabs.forEach(item=>item.classList.toggle('active',item===tab));chapters.forEach(chapter=>chapter.classList.toggle('active',chapter.id===tab.dataset.tab));history.replaceState(null,'','#'+tab.dataset.tab)}});init();</script></body></html>'''


_render_template = render


def render(data: dict) -> str:
    html = _render_template(data)
    html = html.replace("+'</tr>`).join('')", "+`</tr>`).join('')")
    html = html.replace(
        "positive?`rgb(190,${Math.round(115-55*strength)},${Math.round(110-45*strength)})`:`rgb(${Math.round(90-30*strength)},${Math.round(140-35*strength)},${Math.round(190-35*strength)})`",
        "positive?`rgb(190,${Math.round(80+175*(1-strength))},${Math.round(80+175*(1-strength))})`:`rgb(${Math.round(80+175*(1-strength))},${Math.round(80+175*(1-strength))},190)`",
    )
    heatmap = "const loadingValues=Object.values(DATA.loadings).flatMap(row=>Object.values(row));const loadingScale=Math.max(...loadingValues.map(value=>Math.abs(value)));const loadingColor=value=>{const strength=Math.min(1,Math.abs(value)/loadingScale),base=255-175*strength;return value>=0?`rgb(255,${base},${base})`:`rgb(${base},${base},255)`};$('loadingHeatmap').innerHTML='<table><thead><tr><th>Benchmark</th>'+Object.keys(DATA.loadings[DATA.benchmarks[0]]||{}).map(key=>`<th>${key}</th>`).join('')+'</tr></thead><tbody>'+DATA.benchmarks.map(name=>`<tr><td>${name}</td>`+Object.values(DATA.loadings[name]||{}).map(value=>`<td style=\"background:${loadingColor(value)}\">${Number(value).toFixed(3)}</td>`).join('')+'</tr>').join('')+'</tbody></table>';"
    return html.replace("function init(){", heatmap + "function init(){")


def main() -> None:
    OUTPUT.write_text(render(build_payload()), encoding="utf-8")
    print(f"Wrote {OUTPUT.resolve()} ({OUTPUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
